import { Component, ChangeDetectionStrategy, inject, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { CustomExerciseService } from '../../services/custom-exercise.service';
import { ExerciseGeneratorService } from '../../services/ai/exercise-generator.service';
import { ToastService } from '../../services/toast.service';
import { DifficultyLevel, ExerciseCategory } from '../../models/exercise.model';

@Component({
  selector: 'app-exercise-creator',
  imports: [CommonModule, FormsModule],
  templateUrl: './exercise-creator.html',
  styleUrl: './exercise-creator.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ExerciseCreator implements OnInit {
  // Services
  private customExerciseService = inject(CustomExerciseService);
  private exerciseGeneratorService = inject(ExerciseGeneratorService);
  private toastService = inject(ToastService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  // State signals
  exerciseId = signal<string | null>(null);
  isEditMode = computed(() => this.exerciseId() !== null);
  isGenerating = signal(false);
  isSaving = signal(false);
  activeTab = signal<'manual' | 'ai'>('manual');

  // Form signals
  title = signal('');
  sourceText = signal('');
  englishText = signal(''); // Hidden field for AI-generated English translation
  difficulty = signal<DifficultyLevel>(DifficultyLevel.BEGINNER);
  tags = signal<string[]>([]);

  // AI generation
  aiPrompt = signal('');
  vocabularyWords = signal<string[]>([]);
  generationError = signal<string | null>(null);
  hasGeneratedContent = signal(false); // Track if AI has generated content

  // Input fields for adding tags and vocabulary
  newTag = signal('');
  newVocabulary = signal('');

  // Validation errors
  validationErrors = signal<Record<string, string>>({});

  // Enums for template
  DifficultyLevel = DifficultyLevel;
  difficultyLevels = Object.values(DifficultyLevel);

  ngOnInit(): void {
    // Check if we're in edit mode
    this.route.params.subscribe(params => {
      const id = params['id'];
      if (id) {
        this.exerciseId.set(id);
        this.loadExercise(id);
      }
    });
  }

  private loadExercise(id: string): void {
    this.customExerciseService.getCustomExerciseById(id).subscribe(exercise => {
      if (exercise) {
        this.title.set(exercise.title);
        this.sourceText.set(exercise.sourceText);
        this.englishText.set(exercise.englishText || ''); // Load English translation if exists
        this.difficulty.set(exercise.level);
        this.tags.set(exercise.tags || []);
        // Load AI prompt if it was generated by AI
        if (exercise.aiPrompt) {
          this.aiPrompt.set(exercise.aiPrompt);
        }
        // In edit mode, content is already available
        this.hasGeneratedContent.set(true);
      }
    });
  }

  generateWithAI(): void {
    const prompt = this.aiPrompt().trim();
    if (!prompt) {
      this.generationError.set('Please enter a prompt');
      return;
    }

    this.isGenerating.set(true);
    this.generationError.set(null);

    const vocabWords = this.vocabularyWords();
    const vocabularyString = vocabWords.length > 0 ? vocabWords.join(', ') : undefined;

    this.exerciseGeneratorService.generateExercise({
      prompt,
      difficulty: this.difficulty(),
      sourceLanguage: 'Vietnamese',
      targetLanguage: 'English',
      vocabularyWords: vocabularyString
    }).subscribe({
      next: (response) => {
        // Validate that we got proper Vietnamese translation
        if (response.sourceText === response.englishText) {
          this.generationError.set('AI translation failed: Source and English text are identical. Please try again.');
          this.isGenerating.set(false);
          return;
        }
        
        if (this.isLikelyEnglish(response.sourceText)) {
          this.generationError.set('AI translation failed: Generated Vietnamese text appears to be in English. Please try again.');
          this.isGenerating.set(false);
          return;
        }
        
        this.title.set(response.title);
        this.sourceText.set(response.sourceText);
        this.englishText.set(response.englishText || ''); // Store English translation (hidden)
        this.hasGeneratedContent.set(true); // Mark as generated
        this.isGenerating.set(false);
        this.toastService.success('Exercise generated successfully!');
        this.activeTab.set('manual'); // Switch to manual tab to show generated content
      },
      error: (error) => {
        this.generationError.set(error.message);
        this.isGenerating.set(false);
      }
    });
  }

  addTag(): void {
    const tag = this.newTag().trim();
    if (!tag) return;

    const current = this.tags();
    if (current.length >= 10) {
      this.toastService.warning('Maximum 10 tags allowed');
      return;
    }

    if (current.includes(tag)) {
      this.toastService.warning('Tag already added');
      return;
    }

    this.tags.set([...current, tag]);
    this.newTag.set('');
  }

  removeTag(index: number): void {
    const current = this.tags();
    this.tags.set(current.filter((_, i) => i !== index));
  }

  addVocabulary(): void {
    const word = this.newVocabulary().trim();
    if (!word) return;

    const current = this.vocabularyWords();
    if (current.length >= 20) {
      this.toastService.warning('Maximum 20 vocabulary words allowed');
      return;
    }

    if (current.includes(word)) {
      this.toastService.warning('Word already added');
      return;
    }

    this.vocabularyWords.set([...current, word]);
    this.newVocabulary.set('');
  }

  removeVocabulary(index: number): void {
    const current = this.vocabularyWords();
    this.vocabularyWords.set(current.filter((_, i) => i !== index));
  }

  saveExercise(): void {
    // Auto-extract sentences from source text
    const sourceTextValue = this.sourceText();
    const englishTextValue = this.englishText();
    
    // Extract sentences from source text - improved regex to handle quotes
    const sentenceRegex = /[^.!?]+[.!?]+(?=['"]?\s|$)/g;
    let highlightedSentences = sourceTextValue.match(sentenceRegex)?.map(s => s.trim()) || [];
    
    // Filter out invalid sentences (too short or just punctuation)
    highlightedSentences = highlightedSentences.filter(s => {
      const cleanSentence = s.replace(/['".,!?]/g, '').trim();
      return cleanSentence.length > 3; // Must have at least 3 characters of actual content
    });
    
    // Validate that sourceText is in Vietnamese (for AI-generated exercises)
    if (this.hasGeneratedContent()) {
      if (sourceTextValue === englishTextValue) {
        this.validationErrors.set({
          sourceText: 'AI translation failed. Source text and English text are identical. Please try generating again or enter manually.'
        });
        this.toastService.error('AI translation failed. Please try again or enter content manually.');
        return;
      }
      
      if (this.isLikelyEnglish(sourceTextValue)) {
        this.validationErrors.set({
          sourceText: 'Source text appears to be in English instead of Vietnamese. AI translation may have failed. Please try generating again or enter Vietnamese text manually.'
        });
        this.toastService.error('AI translation failed to generate Vietnamese text. Please try again.');
        return;
      }
    }

    // Validate
    const validation = this.customExerciseService.validateExercise({
      title: this.title(),
      sourceText: sourceTextValue,
      highlightedSentences: highlightedSentences,
      level: this.difficulty(),
      customCategories: ['Custom'], // Auto-assign "Custom" category
      tags: this.tags()
    });

    if (!validation.isValid) {
      const errors: Record<string, string> = {};
      validation.errors.forEach(err => {
        errors[err.field] = err.message;
      });
      this.validationErrors.set(errors);
      return;
    }

    this.validationErrors.set({});
    this.isSaving.set(true);

    const exerciseData = {
      title: this.title(),
      sourceText: this.sourceText(),
      englishText: this.englishText(), // Include English translation (will be stored in JSON)
      highlightedSentences: highlightedSentences,
      level: this.difficulty(),
      category: ExerciseCategory.DAILY_LIFE, // Default category
      description: this.title(),
      hints: [],
      customCategories: ['Custom'], // Auto-assign "Custom" category
      tags: this.tags(),
      generatedByAI: this.aiPrompt().trim().length > 0,
      aiPrompt: this.aiPrompt().trim() || undefined
    };

    const operation = this.isEditMode()
      ? this.customExerciseService.updateExercise(this.exerciseId()!, exerciseData)
      : this.customExerciseService.createExercise(exerciseData);

    operation.subscribe({
      next: () => {
        this.isSaving.set(false);
        this.toastService.success(
          this.isEditMode() ? 'Exercise updated successfully!' : 'Exercise created successfully!'
        );
        this.router.navigate(['/exercises/custom']);
      },
      error: (error) => {
        this.isSaving.set(false);
        this.toastService.error(`Failed to save exercise: ${error.message}`);
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/exercises/custom']);
  }

  switchTab(tab: 'manual' | 'ai'): void {
    this.activeTab.set(tab);
    // Reset generated content flag when switching to AI tab
    if (tab === 'ai') {
      this.hasGeneratedContent.set(false);
    }
  }

  onKeyDown(event: KeyboardEvent, action: () => void): void {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      action();
    }
  }

  /**
   * Check if text appears to be in English (simple heuristic)
   */
  private isLikelyEnglish(text: string): boolean {
    if (!text) return false;
    
    // Vietnamese has specific diacritics and characters
    const vietnameseChars = /[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i;
    
    // If text contains Vietnamese characters, it's likely Vietnamese
    if (vietnameseChars.test(text)) {
      return false;
    }
    
    // If text is mostly ASCII and has common English words, likely English
    const commonEnglishWords = /\b(the|and|is|was|are|were|to|in|of|for|with|on|at|from|by|about)\b/gi;
    const matches = text.match(commonEnglishWords);
    
    // If we find 3+ common English words and no Vietnamese chars, likely English
    return matches !== null && matches.length >= 3;
  }
}
